### ISSUE TITLE
'Default Search Query Text' option appears as a searched text instead of a placeholder

### ISSUE THREAD

**Issue by miniol** [WaltRiceJr/Omeka-Plugin-DefaultSearchOptions#1]
The text entered into the 'Default Search Query Text' field of the plugin config form appears in the search form as the 'value' attribute of the 'input' tag. This makes a user to delete this text manually before entering the searched phrase.
My understanding of the  'Default Search Query Text' is a helper text, prompting a user to enter some word into the search form. For such purpose the 'placeholder' attribute should be used.

**Comment by WaltRiceJr** [comment]
Indeed. That's the filter that was available to provide a default search text (as opposed to a search placeholder). Omeka puts that in the search box, the plugin has no control over whether that goes in a placeholder or value.

So from the aspect of this plugin, I don't know how to change that behavior. It does what it is supposed to do. Sorry it isn't quite what you need, though.

**Comment by miniol** [comment]
Ok, clear.
I wonder who really needs the option like this?
BTW, your plugin is really cool and its functionality should be included in the standard Omeka configuration.
